apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  type: NodePort
  ports:
    - name: http
      port: 9000
      targetPort: 9000
    - name: output
      port: 9092
      targetPort: 9092
  selector:
    app: sonarqube